---------------------------------------------------------------------------------
                                --PROFESORES
---------------------------------------------------------------------------------

CREATE TABLE PROFESORES 
(
  ID_PROFESOR NUMBER(9, 0) NOT NULL 
, NOMBRES VARCHAR2(75 BYTE) NOT NULL 
, APELLIDOS VARCHAR2(75 BYTE) NOT NULL 
, RTN VARCHAR2(20 BYTE) NOT NULL 
, DIRECCION VARCHAR2(500 BYTE) 
, TELEFONO VARCHAR2(15 BYTE) NOT NULL 
, ESTADO NUMBER(1, 0) DEFAULT 1 
, CONSTRAINT PROFESORES_PK PRIMARY KEY 
  (
    ID_PROFESOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PROFESORES_PK ON PROFESORES (ID_PROFESOR ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;


---------------------------------------------------------------------------------
                                --ALUMNOS
---------------------------------------------------------------------------------
CREATE TABLE ALUMNOS 
(
  ID_ALUMNO NUMBER(9, 0) NOT NULL 
, NOMBRES VARCHAR2(75 BYTE) NOT NULL 
, APELLIDOS VARCHAR2(75 BYTE) NOT NULL 
, RTN VARCHAR2(20 BYTE) NOT NULL 
, DIRECCION VARCHAR2(500 BYTE) 
, TELEFONO VARCHAR2(20 BYTE) 
, CONSTRAINT ALUMNOS_PK PRIMARY KEY 
  (
    ID_ALUMNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ALUMNOS_PK ON ALUMNOS (ID_ALUMNO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

---------------------------------------------------------------------------------
                                --ASIGNATURAS
---------------------------------------------------------------------------------
CREATE TABLE ASIGNATURAS 
(
  ID_ASIGNATURA NUMBER(9, 0) NOT NULL 
, NOMBRE VARCHAR2(40 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(500 BYTE) 
, CREDITOS VARCHAR2(2 BYTE) NOT NULL 
, HORA_INICIO VARCHAR2(8 BYTE) 
, HORA_FIN VARCHAR2(8 BYTE) 
, CONSTRAINT ASIGNATURAS_PK PRIMARY KEY 
  (
    ID_ASIGNATURA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ASIGNATURAS_PK ON ASIGNATURAS (ID_ASIGNATURA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
---------------------------------------------------------------------------------
                            --ANIO ESCOLAR
---------------------------------------------------------------------------------
CREATE TABLE ANIO_ESCOLAR 
(
  ID_ANIO_ESCOLAR NUMBER NOT NULL 
, ANIO DATE NOT NULL 
, FECHA_INICIO DATE NOT NULL 
, FECHA_FIN DATE NOT NULL 
, CONSTRAINT ANIO_ESCOLAR_PK PRIMARY KEY 
  (
    ID_ANIO_ESCOLAR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ANIO_ESCOLAR_PK ON ANIO_ESCOLAR (ID_ANIO_ESCOLAR ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
---------------------------------------------------------------------------------
                            --NIVEL EDUCATIVO
---------------------------------------------------------------------------------
CREATE TABLE NIVEL_EDUCATIVO 
(
  ID_NIVEL_EDUCATIVO NUMBER(9, 0) NOT NULL 
, NOMBRE VARCHAR2(40 BYTE) NOT NULL 
, SECCION VARCHAR2(1 BYTE) NOT NULL 
, CONSTRAINT NIVEL_EDUCATIVO_PK PRIMARY KEY 
  (
    ID_NIVEL_EDUCATIVO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX NIVEL_EDUCATIVO_PK ON NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
---------------------------------------------------------------------------------
                            --MATRICULAS
---------------------------------------------------------------------------------
CREATE TABLE MATRICULAS 
(
  ID_MATRICULA NUMBER(9, 0) NOT NULL 
, FECHA DATE NOT NULL 
, ID_ANIO_ESCOLAR NUMBER 
, ID_ALUMNO NUMBER 
, ID_NIVEL_EDUCATIVO NUMBER 
, CONSTRAINT MATRICULAS_PK PRIMARY KEY 
  (
    ID_MATRICULA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MATRICULAS_PK ON MATRICULAS (ID_MATRICULA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE MATRICULAS
ADD CONSTRAINT MATRICULAS_ALUMNOS_FK FOREIGN KEY
(
  ID_ALUMNO 
)
REFERENCES ALUMNOS
(
  ID_ALUMNO 
)
ENABLE;

ALTER TABLE MATRICULAS
ADD CONSTRAINT MATRICULAS_ANIOESC_FK FOREIGN KEY
(
  ID_ANIO_ESCOLAR 
)
REFERENCES ANIO_ESCOLAR
(
  ID_ANIO_ESCOLAR 
)
ENABLE;

ALTER TABLE MATRICULAS
ADD CONSTRAINT MATRICULAS_NVLEDUCAT_FK FOREIGN KEY
(
  ID_NIVEL_EDUCATIVO 
)
REFERENCES NIVEL_EDUCATIVO
(
  ID_NIVEL_EDUCATIVO 
)
ENABLE;

---------------------------------------------------------------------------------
                            --NVL_EDUCATIVO_ASIGNATURAS 
---------------------------------------------------------------------------------
CREATE TABLE NVL_EDUCATIVO_ASIGNATURAS 
(
  ID_NIVEL_EDUCATIVO NUMBER 
, ID_ASIGNATURA NUMBER 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE NVL_EDUCATIVO_ASIGNATURAS
ADD CONSTRAINT NVLASIGNTURAS_ASIGNATURA_FK FOREIGN KEY
(
  ID_ASIGNATURA 
)
REFERENCES ASIGNATURAS
(
  ID_ASIGNATURA 
)
ENABLE;

ALTER TABLE NVL_EDUCATIVO_ASIGNATURAS
ADD CONSTRAINT NVLASIGNTURAS_NVLEDUCATIVO_FK FOREIGN KEY
(
  ID_NIVEL_EDUCATIVO 
)
REFERENCES NIVEL_EDUCATIVO
(
  ID_NIVEL_EDUCATIVO 
)
ENABLE;

---------------------------------------------------------------------------------
                            --PROFESORES_ASIGNATURAS_CURSO 
---------------------------------------------------------------------------------
CREATE TABLE PROFESORES_ASIGNATURAS_CURSO 
(
  ID_PROFESOR NUMBER 
, ID_ASIGNATURA NUMBER 
, ID_NIVEL_EDUCATIVO NUMBER 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE PROFESORES_ASIGNATURAS_CURSO
ADD CONSTRAINT PROFASIGC_ASIGNATURA_FK FOREIGN KEY
(
  ID_ASIGNATURA 
)
REFERENCES ASIGNATURAS
(
  ID_ASIGNATURA 
)
ENABLE;

ALTER TABLE PROFESORES_ASIGNATURAS_CURSO
ADD CONSTRAINT PROFASIGC_NVLEDUACT_FK FOREIGN KEY
(
  ID_NIVEL_EDUCATIVO 
)
REFERENCES NIVEL_EDUCATIVO
(
  ID_NIVEL_EDUCATIVO 
)
ENABLE;

ALTER TABLE PROFESORES_ASIGNATURAS_CURSO
ADD CONSTRAINT PROFASIGC_PROFESORES_FK FOREIGN KEY
(
  ID_PROFESOR 
)
REFERENCES PROFESORES
(
  ID_PROFESOR 
)
ENABLE;

---------------------------------------------------------------------------------
                            --CALIFICACIONES 
---------------------------------------------------------------------------------
CREATE TABLE CALIFICACIONES 
(
  ID_CALIFICACION NUMBER(9, 0) NOT NULL 
, NOTA1 NUMBER(3, 0) NOT NULL 
, NOTA2 NUMBER(3, 0) NOT NULL 
, NOTA3 NUMBER(3, 0) NOT NULL 
, NOTA4 NUMBER(3, 0) NOT NULL 
, ID_ALUMNO NUMBER 
, ID_ASIGNATURA NUMBER 
, ID_PROFESOR NUMBER 
, CONSTRAINT CALIFICACIONES_PK PRIMARY KEY 
  (
    ID_CALIFICACION 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CALIFICACIONES_PK ON CALIFICACIONES (ID_CALIFICACION ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE CALIFICACIONES
ADD CONSTRAINT CALIFICACIONES_ALUMNO_FK FOREIGN KEY
(
  ID_ALUMNO 
)
REFERENCES ALUMNOS
(
  ID_ALUMNO 
)
ENABLE;

ALTER TABLE CALIFICACIONES
ADD CONSTRAINT CALIFICACIONES_ASIGNATURA_FK FOREIGN KEY
(
  ID_ASIGNATURA 
)
REFERENCES ASIGNATURAS
(
  ID_ASIGNATURA 
)
ENABLE;

ALTER TABLE CALIFICACIONES
ADD CONSTRAINT CALIFICACIONES_PROFESOR_FK FOREIGN KEY
(
  ID_PROFESOR 
)
REFERENCES PROFESORES
(
  ID_PROFESOR 
)
ENABLE;

---------------------------------------------------------------------------------
                            --ROL
---------------------------------------------------------------------------------
CREATE TABLE ROL 
(
  ID_ROL NUMBER(8, 0) NOT NULL 
, NOMBRE VARCHAR2(40 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(250 BYTE) 
, CONSTRAINT ROL_PK PRIMARY KEY 
  (
    ID_ROL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ROL_PK ON ROL (ID_ROL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
---------------------------------------------------------------------------------
                            --USUARIO
---------------------------------------------------------------------------------

CREATE TABLE USUARIOS 
(
  ID_USUARIO NUMBER(9, 0) NOT NULL 
, NOMBRE VARCHAR2(30 BYTE) NOT NULL 
, PASSWORD VARCHAR2(128 BYTE) NOT NULL 
, ID_ROL NUMBER 
, CONSTRAINT USUARIOS_PK PRIMARY KEY 
  (
    ID_USUARIO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USUARIOS_PK ON USUARIOS (ID_USUARIO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_ROL_FK FOREIGN KEY
(
  ID_ROL 
)
REFERENCES ROL
(
  ID_ROL 
)
ENABLE;

