INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('1', 'Preparatoria', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('2', 'Primer Grado', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('3', 'Primer Grado', 'B');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('4', 'Segundo Grado', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('5', 'Segundo Grado', 'B');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('6', 'Tercer Grado', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('7', 'Tercer Grado', 'B');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('8', 'Cuarto Grado', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('9', 'Cuarto Grado', 'B');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('10', 'Quinto Grado', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('11', 'Quinto Grado', 'B');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('12', 'Sexto Grado', 'A');
INSERT INTO NIVEL_EDUCATIVO (ID_NIVEL_EDUCATIVO, NOMBRE, SECCION) VALUES ('13', 'Sexto Grado', 'B');

SELECT *
    FROM MATRICULAS;    
    
    
--MATRICULA PRIMER GRADO SECCION A
INSERT INTO MATRICULAS (ID_MATRICULA, FECHA, ID_ANIO_ESCOLAR, ID_ALUMNO, ID_NIVEL_EDUCATIVO) VALUES ('1',SYSDATE, '1', '1', '2');    
INSERT INTO MATRICULAS (ID_MATRICULA, FECHA, ID_ANIO_ESCOLAR, ID_ALUMNO, ID_NIVEL_EDUCATIVO) VALUES ('2',SYSDATE, '1', '2', '2');
INSERT INTO MATRICULAS (ID_MATRICULA, FECHA, ID_ANIO_ESCOLAR, ID_ALUMNO, ID_NIVEL_EDUCATIVO) VALUES ('3',SYSDATE, '1', '3', '2');


--MATRICULA SEGUNDO GRADO SECCION A
INSERT INTO MATRICULAS (ID_MATRICULA, FECHA, ID_ANIO_ESCOLAR, ID_ALUMNO, ID_NIVEL_EDUCATIVO) VALUES ('4',SYSDATE, '1', '4', '4');    
INSERT INTO MATRICULAS (ID_MATRICULA, FECHA, ID_ANIO_ESCOLAR, ID_ALUMNO, ID_NIVEL_EDUCATIVO) VALUES ('5',SYSDATE, '1', '5', '4');


--INICIO PROCEDIMINETOS ALMACENADOS








