--------------------------------------------------------
--  File created - Saturday-March-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body ANIO_ESCOLARR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "ANIO_ESCOLARR" AS 
    PROCEDURE INSERTAR_ANIO_ESCOLAR (
        V_ANIO IN DATE,
        V_FECHA_INICIO IN DATE,
        V_FECHA_FIN IN DATE
    )
AS BEGIN
    INSERT INTO ANIO_ESCOLAR VALUES(INCREMENT_ID_ANIO_ESCOLAR,V_ANIO,V_FECHA_INICIO,V_FECHA_FIN);
END INSERTAR_ANIO_ESCOLAR;  

-----------------
FUNCTION INCREMENT_ID_ANIO_ESCOLAR RETURN NUMBER AS 
    V_ID_ANIOESCOLAR NUMBER;
BEGIN
    SELECT SEQ_ANIO_ESCOLAR.NEXTVAL
        INTO V_ID_ANIOESCOLAR
        FROM DUAL;
    RETURN V_ID_ANIOESCOLAR;    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error INCREMENT_ID_ANIO_ESCOLAR: '||SQLERRM);
END INCREMENT_ID_ANIO_ESCOLAR;

--------
FUNCTION EXISTE_ANIO_ESCOLAR(V_ANIO IN DATE) RETURN BOOLEAN AS 
        v_contador NUMBER;
    BEGIN
        SELECT count(1)
            INTO v_contador
            FROM ANIO_ESCOLAR
        WHERE EXTRACT( YEAR FROM ANIO ) = EXTRACT( YEAR FROM V_ANIO );    
            RETURN (v_contador > 0);
    END EXISTE_ANIO_ESCOLAR; 
    
PROCEDURE SP_LISTAR_ANIO_ESCOLAR (
    C_LISTA OUT SYS_REFCURSOR
)
IS BEGIN
    OPEN C_LISTA FOR
        SELECT ID_ANIO_ESCOLAR, ANIO, FECHA_INICIO, FECHA_FIN
            FROM ANIO_ESCOLAR;
END SP_LISTAR_ANIO_ESCOLAR;


PROCEDURE SP_ACTUALIZAR_ANIO_ESCOLAR (
        V_ID_ANIO_ESCOLAR IN NUMBER,
        V_ANIO IN DATE,
        V_FEHCA_INICIO IN DATE,
        V_FECHA_FIN IN DATE,
        V_ERROR IN OUT NUMBER,
        V_DESCRIPCION_ERR IN OUT VARCHAR2
) AS
BEGIN
    V_ERROR := 0;
    UPDATE anio_escolar
        SET ANIO = V_ANIO, fecha_inicio = V_FEHCA_INICIO, fecha_fin = V_FECHA_FIN
        WHERE ID_ANIO_ESCOLAR = V_ID_ANIO_ESCOLAR;
EXCEPTION
    WHEN OTHERS THEN
    V_ERROR := 1;
    V_DESCRIPCION_ERR := SQLERRM;
END SP_ACTUALIZAR_ANIO_ESCOLAR;

END ANIO_ESCOLARR;
