--------------------------------------------------------
--  File created - Saturday-March-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body ASIGNATURA_DB
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "ASIGNATURA_DB" AS
PROCEDURE INSERTAR_ASIGNATURA(
     A_NOMBRE IN VARCHAR2,
     A_DESCRIPCION IN VARCHAR2,
     A_CREDITOS IN VARCHAR2,
     A_HORA_INICIO IN VARCHAR2,
     A_HORA_FIN IN VARCHAR2
)AS BEGIN

    INSERT INTO ASIGNATURAS(ID_ASIGNATURA, NOMBRE, DESCRIPCION, CREDITOS, HORA_INICIO,HORA_FIN) 
       VALUES (INCREMENT_ID_ASIGNATURA,A_NOMBRE,A_DESCRIPCION, A_CREDITOS,A_HORA_INICIO,A_HORA_FIN);  
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error OBTENER SIGUIENTE_CODIGO: '||SQLERRM);
END INSERTAR_ASIGNATURA;


FUNCTION INCREMENT_ID_ASIGNATURA RETURN NUMBER AS 
    v_codigo_asignatura NUMBER;
BEGIN
    SELECT nvl(MAX(ID_ASIGNATURA),0)+1
    INTO v_codigo_asignatura
    FROM ASIGNATURAS;
    IF v_codigo_asignatura IS NULL THEN
        RETURN 1;
    ELSE
        RETURN v_codigo_asignatura;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error OBTENER SIGUIENTE_CODIGO: '||SQLERRM);
END INCREMENT_ID_ASIGNATURA;

PROCEDURE ACTUALIZAR_ASIGNATURA (
     A_ID_ASIGNATURA NUMBER,
     A_NOMBRE IN VARCHAR2,
     A_DESCRIPCION IN VARCHAR2,
     A_CREDITOS IN VARCHAR2,
     A_HORA_INICIO IN VARCHAR2,
     A_HORA_FIN IN VARCHAR2
) AS
BEGIN
    UPDATE ASIGNATURAS
        SET NOMBRE = A_NOMBRE,DESCRIPCION = A_DESCRIPCION,CREDITOS = A_CREDITOS,HORA_INICIO = A_HORA_INICIO,HORA_FIN = A_HORA_FIN
        WHERE ID_ASIGNATURA = A_ID_ASIGNATURA;
EXCEPTION
    WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('Error ACTUALIZAR LA ASIGNATURA: '||SQLERRM);
END ACTUALIZAR_ASIGNATURA;

 PROCEDURE BUSCAR_ASIGNATURAS (CURSOR_ASIGNATURA OUT SYS_REFCURSOR)
IS BEGIN
    OPEN CURSOR_ASIGNATURA FOR
    SELECT ID_ASIGNATURA, NOMBRE,DESCRIPCION,CREDITOS,HORA_INICIO,HORA_FIN
        FROM ASIGNATURAS ORDER BY ID_ASIGNATURA;
END BUSCAR_ASIGNATURAS;

PROCEDURE BUSCAR_ID_ASIGNATURA (
    V_ID_ASIGNATURA IN NUMBER,
    C_BUSQ_ASIGNATURA OUT SYS_REFCURSOR
)
IS BEGIN
    OPEN C_BUSQ_ASIGNATURA FOR
    SELECT NOMBRE,DESCRIPCION,CREDITOS,HORA_INICIO,HORA_FIN
        FROM ASIGNATURAS
    WHERE ID_ASIGNATURA = V_ID_ASIGNATURA;
END BUSCAR_ID_ASIGNATURA;

FUNCTION ASIGNATURA_YA_REGISTRADO(V_NOMBRE IN VARCHAR2) RETURN BOOLEAN AS 
        v_contador NUMBER;
    BEGIN
        SELECT count(1)
            INTO v_contador
            FROM ASIGNATURAS
        WHERE UPPER(NOMBRE) = UPPER(V_NOMBRE);
        RETURN (v_contador > 0);
    END ASIGNATURA_YA_REGISTRADO;

END ASIGNATURA_DB;
