--------------------------------------------------------
--  File created - Saturday-March-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package ASIGNATURA_DB
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "ASIGNATURA_DB" AS
PROCEDURE INSERTAR_ASIGNATURA(
     A_NOMBRE IN VARCHAR2,
     A_DESCRIPCION IN VARCHAR2,
     A_CREDITOS IN VARCHAR2,
     A_HORA_INICIO IN VARCHAR2,
     A_HORA_FIN IN VARCHAR2
);

   FUNCTION INCREMENT_ID_ASIGNATURA RETURN NUMBER;

     PROCEDURE ACTUALIZAR_ASIGNATURA (
     A_ID_ASIGNATURA NUMBER,
     A_NOMBRE IN VARCHAR2,
     A_DESCRIPCION IN VARCHAR2,
     A_CREDITOS IN VARCHAR2,
     A_HORA_INICIO IN VARCHAR2,
     A_HORA_FIN IN VARCHAR2
);

    PROCEDURE BUSCAR_ASIGNATURAS (CURSOR_ASIGNATURA OUT SYS_REFCURSOR);

    PROCEDURE BUSCAR_ID_ASIGNATURA (
    V_ID_ASIGNATURA IN NUMBER,
    C_BUSQ_ASIGNATURA OUT SYS_REFCURSOR
    );
    
    FUNCTION ASIGNATURA_YA_REGISTRADO(V_NOMBRE IN VARCHAR2) RETURN BOOLEAN;

END ASIGNATURA_DB;
