--------------------------------------------------------
--  File created - Saturday-March-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package PROFESORES_ASIG_CURSO_DB
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PROFESORES_ASIG_CURSO_DB" AS
    PROCEDURE SP_BUSQUEDA_ID_PROFESOR (
    V_ID_PROFESOR IN NUMBER,
    C_BUSQUEDA_PROFESOR OUT SYS_REFCURSOR
);
--
PROCEDURE SP_ASIGNATURA (
    C_LISTA_ASIGNATURA OUT SYS_REFCURSOR
);

--
PROCEDURE SP_LISTAR_ASIGN_ID (
    V_ID_PROFESOR IN NUMBER,
    V_ID_NVL_EDUCATIVO IN NUMBER,
    C_LISTA_RESULTANTE OUT SYS_REFCURSOR
);

--
PROCEDURE SP_INSERTAR_ASIG_PROFESORES (
    V_ID_PROFESOR NUMBER,
    V_ID_ASIGNATURA NUMBER,
    V_ID_NIVEL_EDUCATIVO NUMBER
);

--
PROCEDURE SP_ASIGNATURA_LISTA (
    V_BUSQUEDA IN VARCHAR2,
    C_LISTA_ASIGNACIONES OUT SYS_REFCURSOR
);

PROCEDURE SP_GRADOS_LISTA (
    C_LISTA_GRADOS OUT SYS_REFCURSOR
);

PROCEDURE ELIMINAR_PROF_ASIG_CUR(
    V_ID_PROFESOR NUMBER ,
    V_ID_GRADO NUMBER
);

FUNCTION VALIDAR_CLASE_GRADO(V_ID_ASIGNATURA IN NUMBER, V_ID_GRADO NUMBER) RETURN BOOLEAN;

FUNCTION LIMITE_ASIGN_PROFESOR(V_ID_PROFESOR NUMBER) RETURN NUMBER;

END PROFESORES_ASIG_CURSO_DB;
