--------------------------------------------------------
--  File created - Saturday-March-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PROFESORES_ASIG_CURSO_DB
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "PROFESORES_ASIG_CURSO_DB" AS
PROCEDURE SP_BUSQUEDA_ID_PROFESOR (
    V_ID_PROFESOR IN NUMBER,
    C_BUSQUEDA_PROFESOR OUT SYS_REFCURSOR
)
IS BEGIN
    OPEN C_BUSQUEDA_PROFESOR FOR
    SELECT ID_PROFESOR, NOMBRES||' '||APELLIDOS
        FROM PROFESORES
    WHERE ID_PROFESOR = V_ID_PROFESOR;    
END SP_BUSQUEDA_ID_PROFESOR; 

--
    PROCEDURE SP_ASIGNATURA (
    C_LISTA_ASIGNATURA OUT SYS_REFCURSOR
    )
    IS BEGIN
        OPEN C_LISTA_ASIGNATURA FOR
        SELECT ID_ASIGNATURA, NOMBRE
            FROM ASIGNATURAS;
    END SP_ASIGNATURA; 
    
--
    PROCEDURE SP_LISTAR_ASIGN_ID (
    V_ID_PROFESOR IN NUMBER,
    V_ID_NVL_EDUCATIVO IN NUMBER,
    C_LISTA_RESULTANTE OUT SYS_REFCURSOR
)
IS BEGIN
    OPEN C_LISTA_RESULTANTE FOR
        SELECT pac.id_asignatura, a.nombre
            FROM PROFESORES_ASIGNATURAS_CURSO PAC INNER JOIN ASIGNATURAS A ON pac.id_asignatura = a.id_asignatura
            INNER JOIN PROFESORES P ON pac.id_profesor = p.id_profesor
            INNER JOIN NIVEL_EDUCATIVO NE ON pac.id_nivel_educativo = ne.id_nivel_educativo
    WHERE pac.id_profesor = V_ID_PROFESOR
        AND pac.id_nivel_educativo = V_ID_NVL_EDUCATIVO;
END SP_LISTAR_ASIGN_ID;
    
--
PROCEDURE SP_INSERTAR_ASIG_PROFESORES (
    V_ID_PROFESOR NUMBER,
    V_ID_ASIGNATURA NUMBER,
    V_ID_NIVEL_EDUCATIVO NUMBER
) AS
BEGIN
    INSERT INTO profesores_asignaturas_curso(ID_PROFESOR,ID_ASIGNATURA, id_nivel_educativo) 
       VALUES (V_ID_PROFESOR,V_ID_ASIGNATURA,V_ID_NIVEL_EDUCATIVO);  
END SP_INSERTAR_ASIG_PROFESORES;
    
    PROCEDURE SP_ASIGNATURA_LISTA (
    V_BUSQUEDA IN VARCHAR2,
    C_LISTA_ASIGNACIONES OUT SYS_REFCURSOR
)
IS BEGIN
    OPEN C_LISTA_ASIGNACIONES FOR
        SELECT pac.id_profesor, p.nombres||' '||p.apellidos, PAC.ID_ASIGNATURA, a.nombre, pac.id_nivel_educativo, ne.nombre, ne.seccion
        FROM PROFESORES_ASIGNATURAS_CURSO PAC INNER JOIN PROFESORES P ON PAC.ID_PROFESOR = P.ID_PROFESOR
        INNER JOIN ASIGNATURAS A ON PAC.ID_ASIGNATURA = A.ID_ASIGNATURA
        INNER JOIN NIVEL_EDUCATIVO NE ON PAC.ID_NIVEL_EDUCATIVO = NE.ID_NIVEL_EDUCATIVO
        WHERE P.NOMBRES LIKE '%'||V_BUSQUEDA||'%'
        ORDER BY  p.nombres;    
    END SP_ASIGNATURA_LISTA;
    
    PROCEDURE SP_GRADOS_LISTA (
    C_LISTA_GRADOS OUT SYS_REFCURSOR
)
IS BEGIN
    OPEN C_LISTA_GRADOS FOR
    SELECT ID_NIVEL_EDUCATIVO, NOMBRE, SECCION
        FROM NIVEL_EDUCATIVO;
END SP_GRADOS_LISTA;
    
    
    PROCEDURE ELIMINAR_PROF_ASIG_CUR(
    V_ID_PROFESOR NUMBER ,
    V_ID_GRADO NUMBER
    )
    AS BEGIN
        DELETE FROM PROFESORES_ASIGNATURAS_CURSO WHERE ID_PROFESOR = V_ID_PROFESOR AND id_nivel_educativo = V_ID_GRADO;
END ELIMINAR_PROF_ASIG_CUR; 
    
FUNCTION VALIDAR_CLASE_GRADO(V_ID_ASIGNATURA IN NUMBER, V_ID_GRADO NUMBER) RETURN BOOLEAN AS 
        v_contador NUMBER;
    BEGIN
        SELECT count(1)
            INTO v_contador
            FROM PROFESORES_ASIGNATURAS_CURSO
        WHERE ID_ASIGNATURA = V_ID_ASIGNATURA
        AND ID_NIVEL_EDUCATIVO = V_ID_GRADO;                
            RETURN (v_contador > 0);
    END VALIDAR_CLASE_GRADO; 
    
FUNCTION LIMITE_ASIGN_PROFESOR(V_ID_PROFESOR NUMBER) RETURN NUMBER AS
    CURSOR C_CURSOR_VALIDAR IS
        SELECT ID_ASIGNATURA
            FROM PROFESORES_ASIGNATURAS_CURSO
        WHERE ID_PROFESOR = V_ID_PROFESOR;
      total_resultados NUMBER;
    BEGIN

  FOR ITEM IN C_CURSOR_VALIDAR LOOP
     total_resultados :=C_CURSOR_VALIDAR%ROWCOUNT;
 END LOOP;
 RETURN total_resultados;
END LIMITE_ASIGN_PROFESOR;    
    
END PROFESORES_ASIG_CURSO_DB;
