--------------------------------------------------------
--  File created - Saturday-March-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body USUARIOS_DB
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "USUARIOS_DB" AS
    PROCEDURE SP_INSERTAR_USUARIO (
    V_USUARIO VARCHAR2,
    V_PASWORD VARCHAR2,
    V_ID_ROL NUMBER,
    V_ERROR OUT NUMBER,
    V_DESCRIPCION OUT VARCHAR2
) AS
BEGIN 
     V_ERROR := 0;
    INSERT INTO USUARIOS(ID_USUARIO, NOMBRE, PASSWORD, ID_ROL) 
        VALUES (INCREMENT_ID_USUARIOS,V_USUARIO,V_PASWORD,V_ID_ROL);
    EXCEPTION
        WHEN OTHERS THEN 
             V_ERROR := 1;
             V_DESCRIPCION := SQLERRM;
     END SP_INSERTAR_USUARIO;
     
     --FUNCION
     FUNCTION INCREMENT_ID_USUARIOS RETURN NUMBER AS 
        V_CODIGO_USUARIO NUMBER;
    BEGIN
        SELECT nvl(MAX(ID_USUARIO),0)+1
        INTO V_CODIGO_USUARIO
        FROM USUARIOS;
        IF V_CODIGO_USUARIO IS NULL THEN
            RETURN 1;
        ELSE
            RETURN V_CODIGO_USUARIO;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error OBTENER SIGUIENTE_CODIGO_DEP: '||SQLERRM);
    END INCREMENT_ID_USUARIOS;
    
    --ACTUALIZAR
    PROCEDURE ACTUALIZAR_USUARIO (
    V_ID_USUARIO NUMBER,
    V_USUARIO VARCHAR,
    V_PASSWORD VARCHAR,
    V_ID_ROL NUMBER,
    V_ERROR OUT NUMBER,
    V_DESCRIPCION_ERR OUT VARCHAR2
) AS
BEGIN
    V_ERROR := 0;
    UPDATE USUARIOS
        SET NOMBRE = V_USUARIO, PASSWORD = V_PASSWORD, ID_ROL = v_id_rol
        WHERE ID_USUARIO = V_ID_USUARIO;
EXCEPTION
    WHEN OTHERS THEN
    V_ERROR := 1;
    V_DESCRIPCION_ERR := SQLERRM;
END ACTUALIZAR_USUARIO;
    
    
    --LISTAR ROLES
    PROCEDURE SP_LISTAR_ROLES (
    C_CURSOR OUT SYS_REFCURSOR
    )
    IS BEGIN
        OPEN C_CURSOR FOR
        SELECT *
            FROM ROL;
END SP_LISTAR_ROLES;
    
    --LISTAR USUARIOS
    PROCEDURE SP_USUARIO_LISTA (
        V_BUSQUEDA IN VARCHAR2,
        C_LISTA_USUARIO OUT SYS_REFCURSOR
    )
    IS BEGIN
    OPEN C_LISTA_USUARIO FOR
        SELECT A.ID_USUARIO, A.nombre, A.ID_ROL, r.nombre, a.password
        FROM USUARIOS A INNER JOIN ROL R ON A.ID_ROL = R.ID_ROL
        WHERE A.nombre LIKE '%'||V_BUSQUEDA||'%';    
END SP_USUARIO_LISTA;
    
    PROCEDURE SP_LOGIN (
        V_USUARIO VARCHAR2,
        V_PASSWORD VARCHAR2,
        C_CURSOR_LOGIN OUT SYS_REFCURSOR
    )
IS BEGIN
    OPEN C_CURSOR_LOGIN FOR
    SELECT U.ID_USUARIO, U.NOMBRE, U.ID_ROL, R.NOMBRE, U.PASSWORD
        FROM USUARIOS U INNER JOIN ROL R ON U.ID_ROL = R.ID_ROL
    WHERE U.NOMBRE = V_USUARIO AND U.PASSWORD = V_PASSWORD;    
END SP_LOGIN;
    
    
    
END USUARIOS_DB;
